# Generated by Django 4.1 on 2022-09-04 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_product_cart_product_rename_user_cart_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='mobile',
            field=models.IntegerField(default='9823876456'),
            preserve_default=False,
        ),
    ]
